// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRg4MjkIlI_SHCT3MG7aeymnZL1C7laU',
    appId: '1:482856935751:web:adab3072e27d9ef24c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    authDomain: 'lami1a-1.firebaseapp.com',
    databaseURL: 'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5qiSXqBKE6rbtzbY790bfVdSz5B01vA4',
    appId: '1:482856935751:android:852e18c8aec9457e4c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    databaseURL: 'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7QouB-nK0TfXe4XfPHkjmr-8ODP9CzQ',
    appId: '1:482856935751:ios:34a714d04fc15dfd4c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    databaseURL: 'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
    iosClientId: '482856935751-i3vrltu3sihoj051p5sajcv7n7rs8pvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.liisma1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7QouB-nK0TfXe4XfPHkjmr-8ODP9CzQ',
    appId: '1:482856935751:ios:5442d0a15b95c6104c2c62',
    messagingSenderId: '482856935751',
    projectId: 'lami1a-1',
    databaseURL: 'https://lami1a-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lami1a-1.appspot.com',
    iosClientId: '482856935751-9nlh169pebo4bmcme3mmmfafuku0oi58.apps.googleusercontent.com',
    iosBundleId: 'com.example.liisma1.RunnerTests',
  );
}
